# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a838fd3d7af33bb086a4de2ff620ff960da9f63305eeb67f33d0a51969485767fcd658cb114e8a0a36f66eab132c0062a4134be4118486568cac7f083c3b4f35

test:
  secret_key_base: b8f7f7ca0553e723bab40af657c2393ced8563bb694d8f6a6ebbf7570e97e0e25d075fdca9bb60246b68ca99fb3e188d5cff60fcb39b57edd41186fc06c7b5de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
